[WIP] Add image encoder base
VIDA-NYU/alpha-automl pull request #61
Opened 2023-08-16 18:16 UTC by EdenWuyifan

2023-10-03 17:07 UTC, roquelopez requested changes
In general it looks good, thanks! Please address my comments!

2023-10-03 17:07 UTC, roquelopez commented on tests/test_data/image_dataset_2/tables/learningData.csv
Remove the d3mIndex column. Avoid to use the name `learningData.csv`. Use something more descriptive, e.g. digits.csv, etc. It's not necessary to have the folder `tables`. Change the name `image_dataset_2` to `digits`

2023-10-03 17:07 UTC, roquelopez commented on examples/adding_clip_primitives.ipynb
Add only one example for image classification. Add the link to download the dataset in the jupyter notebook. This link should contain the trian_data.csv and test_data.csv files (use the same names that we have in the other example to be consistent). Avoid to split the data in the jupyter notebook. The less code we put in our example, the better.

2023-10-10 16:17 UTC, roquelopez commented
I made some minor changes. Feel free to merge it.

2023-10-11 16:57 UTC, EdenWuyifan commented
I fixed some bugs and new it is ready to merge

2023-10-11 16:57 UTC, merged